### PR TITLE
Ensure form post is escaped

### PR DESCRIPTION
**Pull request by dave-ledgy**
Currently if the RelayState contains double quotes, the createFormPost method will copy that directly to the HTML, resulting in something along the lines of: `<input type="hidden" name="RelayState" value="{"someProperty":"someValue"}"/>`, which will result in invalid RelayState of `{` being posted to the ACS endpoint. This PR replace instances of `"` in the RelayState with `&quot;` so that the RelayState sent to the ACS is accurate.

### CODE REVIEW

**Comment by deepakprabhakara** [comment]
Thanks for reporting this @dave-ledgy

**Comment by niwsa** [comment]
@dave-ledgy Even better we could escape few more characters ... See https://stackoverflow.com/a/6234804/3939061

**Review by deepakprabhakara — APPROVED** [review]

**Comment by deepakprabhakara** [comment]
Thanks @dave-ledgy, available in v1.4.12

**Comment by dave-ledgy** [comment]
Awesome thanks @deepakprabhakara ! Would it be possible to also publish a new version of https://github.com/boxyhq/mock-saml with this fix?

**Comment by deepakprabhakara** [comment]
@dave-ledgy Will do that shortly

**Comment by deepakprabhakara** [comment]
@dave-ledgy Done, Mock SAML v1.3.5

**Pull request merged**
